$(function(){$("#jumper").show();FixTopJumper();$(window).bind("scroll resize",function(){FixTopJumper()});JumperAnimateEvent("jumpTop")});function FixTopJumper(){$(window).width();var a=$(window).height(),b=$(document).scrollTop();b>=a/3?$("#jumpTop").show():$("#jumpTop").hide();$("#jumper").css("top",b+a-150).css("right",10)}
function JumperAnimateEvent(a){$("#"+a).click(function(){var b=$(this).attr("data-scroll").substr(1);b=$("#"+b).offset().top;$("html,body").animate({scrollTop:b},500,function(){})})}function FixImageSize(a,b,c){$(a).each(function(){var f=$(this),d=f.width(),e=f.height();d>=b&&f.width(b);typeof c!="undefined"&&e>=c&&f.height(c)})}
function InitMenus(a,b,c){var f=0;$(a).each(function(){var d=$(this);if(f==0){var e=d.attr("data");$(a).each(function(){$(this).removeClass(c)});$(b).each(function(){$(this).hide()});d.hasClass(c)||d.addClass(c);$("#"+e).show()}d.bind("click",function(){var g=$(this),h=g.attr("data");$(a).each(function(){$(this).removeClass(c)});$(b).each(function(){$(this).hide()});g.hasClass(c)||g.addClass(c);$("#"+h).show()});f++})}
function FixHeadOpacity(a,b){var c=$("#head");c=typeof a!="undefined"?$("#"+a):$("#head");if(typeof b=="undefined")b=56;$(document).scrollTop()>b?c.css({opacity:0.8}):c.css({opacity:1})}
function SubmitPostCommentForm(a,b){a=$("#"+a);var c=$("#"+b);c.attr("disabled",true);b=a.attr("action");if(b.indexOf("__AJAX=True")<0)b+="&__AJAX=True";b+="&rand="+new Date;a=$("#txtAuthorName").val();var f=$("#txtAuthorEmail").val(),d=$("#txtContent").val();$.post(b,{AuthorName:a,AuthorEmail:f,Content:d},function(e){e=eval(e);var g=e.Data,h=parseInt(e.Result);alert(e.Message);h>0&&g.Validated&&location.reload();c.attr("disabled",false)});return false}
function SubmitPostEmailForm(a,b){a=$("#"+a);var c=$("#"+b);c.attr("disabled",true);b=a.attr("action");if(b.indexOf("__AJAX=True")<0)b+="&__AJAX=True";b+="&rand="+new Date;a=$("#txtEmailTitle").val();var f=$("#txtEmailSender").val(),d=$("#txtEmailContent").val();$.post(b,{EmailTitle:a,EmailSender:f,EmailContent:d},function(e){e=eval(e);var g=parseInt(e.Result);alert(e.Message);c.attr("disabled",false)});return false}
function GotoGoogleTranslator(a,b,c){var f=($.browser.msie&&parseFloat($.browser.version)<=6)==false;a=a+"|"+b;c=typeof c=="undefined"||c==true;var d=unescape(document.location.toString());var e=b="";if(d.indexOf("translate_c?")!=-1){b=d.indexOf("u=");if(b==-1)b=document.location;else{b=d.substring(b,d.length).split("&");b=b[0].substring(2,b[0].length)}}else b=document.location;d="";if(a.indexOf("|")==-1){indexof_p1=a.indexOf("><");if(indexof_p1==-1){e=a;if(a=="en")d=1}else{a=a.split("><");e=a[0]+
"|"+a[1];if(a[1]=="en")d=1}}else{a=a.split("|");e=a[0]+"|"+a[1];if(a[1]=="en")d=1}a="";a=d==1?b:"http://translate.google.com/translate_c?langpair="+e+"&u="+b;if(c)if(f){msgWindow=window.open("","subwindow","toolbar=yes,location=yes,directories=yes,status=yes,scrollbars=yes,menubar=yes,resizable=yes,left=0,top=0");msgWindow.focus();msgWindow.location.href=a}else msgWindow=window.open(a,"subwindow","toolbar=yes,location=yes,directories=yes,status=yes,scrollbars=yes,menubar=yes,resizable=yes,left=0,top=0");
else window.location.href=a};
