$(function(){$("#jumper").show();FixHeightWidth();FixTopJumper();$(window).bind("scroll resize",function(){FixHeightWidth();FixTopJumper()});JumperAnimateEvent("jumpTop")});function FixHeightWidth(){$(window).width();var a=$(window).height(),c=$(document).scrollTop(),d=$("#footer");if(d[0]){a=a+c-d.height();d.css({position:"absolute",top:a})}}
function JumperAnimateEvent(a){$("#"+a).click(function(){var c=$(this).attr("data-scroll").substr(1);c=$("#"+c).offset().top;$("html,body").animate({scrollTop:c},500,function(){})})}function FixTopJumper(){$(window).width();var a=$(window).height(),c=$(document).scrollTop();c>=a/3?$("#jumpTop").show():$("#jumpTop").hide();$("#jumper").css("top",c+a-100).css("right",10)}
function CheckAllItems(a,c,d){var h=$("#"+a).attr("checked");$("input[name='"+c+"']").each(function(){var g=$(this);if(g.attr("type").toLowerCase()=="checkbox")h?g.attr("checked","checked"):g.removeAttr("checked")});if(d)h?$("#"+d).attr("checked","checked"):$("#"+d).removeAttr("checked")}
function QueryAction(a,c,d,h){if(a.indexOf("__AJAX=True")<0)a+="&__AJAX=True";a+="&rand="+new Date;$.get(a,function(g){var i=eval(g);g=parseInt(i.Result);var j=i.Message,e=true;if(h)e=h(i);if(e==false)return false;if(c&&d){var b=$("#"+c);e=$("#"+d);if(b[0]&&e[0]){i=e.offset().top;e=e.offset().left;b.show();b.html(j);b.css({position:"absolute",top:i,left:e});switch(g){case 1:b.removeClass("Failed");b.removeClass("Default");b.hasClass("Success")||b.addClass("Success");break;case -1:b.removeClass("Success");
b.removeClass("Default");b.hasClass("Failed")||b.addClass("Failed");break;case 0:default:b.removeClass("Success");b.removeClass("Failed");b.hasClass("Default")||b.addClass("Default");break}setTimeout(function(){b.fadeOut(500)},1500)}else alert(j)}else alert(j)})}
function PostAction(a,c,d,h,g){if(a.indexOf("__AJAX=True")<0)a+="&__AJAX=True";a+="&rand="+new Date;$.post(a,c,function(i){var j=eval(i);i=parseInt(j.Result);var e=j.Message,b=true;if(g)b=g(j);if(b==false)return false;if(d&&h){var f=$("#"+d);b=$("#"+h);if(f[0]&&b[0]){j=b.offset().top;b=b.offset().left;f.show();f.html(e);f.css({position:"absolute",top:j,left:b});switch(i){case 1:f.removeClass("Failed");f.removeClass("Default");f.hasClass("Success")||f.addClass("Success");break;case -1:f.removeClass("Success");
f.removeClass("Default");f.hasClass("Failed")||f.addClass("Failed");break;case 0:default:f.removeClass("Success");f.removeClass("Failed");f.hasClass("Default")||f.addClass("Default");break}setTimeout(function(){f.fadeOut(500)},1500)}else alert(e)}else alert(e)})}function QueryLinkAction(a,c,d){if(window.confirm(c)){c=$("#"+a).attr("href");QueryAction(c,"ActionMessageBox",a,function(h){return d(h)});return false}return false}
function YesOrNoShowOrHide(a,c){a=$("#"+a);c=$("#"+c);a.val()=="True"?c.show():c.hide()}function ShowAttachRenamePanel(a){var c=$("#AttachItemPanel_"+a),d=$("#AttachRenamePanel_"+a);a=$("#AttachName_"+a);c.hide();d.show();a.focus();return false}
function RenameAttach(a,c){if(c.indexOf("__AJAX=True")<0)c+="&__AJAX=True";var d=$("#AttachItemPanel_"+a),h=$("#AttachRenamePanel_"+a),g=$("#linkAttachName_"+a),i=g.html(),j=$("#AttachName_"+a).val();$.post(c,{AttachId:a,Name:j},function(e){var b=eval(e);e=parseInt(b.Result);b=b.Message;if(e<=0)alert(b);else{e=i.substring(i.indexOf(".")+1);g.html(j+"."+e)}});d.show();h.hide()};
