var a;$(function(){FixThumbLogo()});function LoadChildCategoryList(b,c,d){if(b.indexOf("__AJAX=True")<0)b+="&__AJAX=True";$.get(b,null,function(e){var g=$("#"+c);g.html("");if(d)for(var f in d)g.append('<option value="'+f+'">'+d[f]+"</option>");e=eval(e).Data;for(f=0;f<e.length;f++){var h=e[f];g.append('<option value="'+h.CategoryId+'">'+h.Name+"("+h.UrlName+")</option>")}})}function FixThumbLogo(){$(".product_img img").each(function(){var b=$(this);b.width()>=300&&b.width(300)})}
function DeleteProductThumb(b,c){window.confirm(c)&&QueryAction(b,"PageActionMessageBox","ThumbImageLink",function(d){$("#ThumbImagePanel").fadeOut(200)});return false}function DeleteProductLogo(b,c){window.confirm(c)&&QueryAction(b,"PageActionMessageBox","LogoImageLink",function(d){$("#LogoImagePanel").fadeOut(200)});return false}
function DeleteProducts(b,c){if(window.confirm(c)){b=$("#"+b).attr("action");var d=[];$("input[name='ProductIds']").each(function(){var e=$(this);e.attr("checked")&&d.push(e.val())});c={ProductIds:d.join(",")};PostAction(b,c,"ActionMessageBox","SubmitDeleteChecked",function(e){var g=parseInt(e.Result);if(e=eval(e.Data))for(g=0;g<e.length;g++){var f=$("#productItem_"+e[g]);f.fadeOut(400);setTimeout(function(){f.remove()},500)}return true})}return false}
function BindDeleteAttachFunction(b){$("#ProductAttachList .delete_attach_btn").each(function(){var c=$(this),d=c.attr("id");c.unbind("click");c.bind("click",function(){QueryLinkAction(d,b,function(e){var g=parseInt(e.Result),f=$("#AttachListItem_"+e.Data);f.fadeOut(400);setTimeout(function(){f.remove()},500);return true});return false})})}
function ProductAttributeBuilder(b,c){this.TemplateId=b;this.ContainerId=c;this.IndexCookieKey="ProductAttributePanelIndex_"+this.TemplateId+"_"+this.ContainerId;this.WriteIndexesCookie("")}a=ProductAttributeBuilder.prototype;a.TemplateId=null;a.ContainerId=null;a.IndexCookieKey=null;
a.AddProductAttributePanel=function(){var b=parseInt($.cookie(this.IndexCookieKey));if(isNaN(b))b=1;else b+=1;ParseTemplate(this.TemplateId,this.ContainerId,{index:b});this.WriteIndexesCookie(b);$("#ProductAttributePanel_"+b).fadeIn(500);var c=$("#ProductAttributePanelIndexes").val();c=c==""?[]:c.split(",");$.inArray(b,c)<0&&c.push(b);c=c.join(",");$("#ProductAttributePanelIndexes").val(c)};
a.RemoveProductAttributePanel=function(b,c){var d=$("#"+b);if(d[0]){d.fadeOut(500);setTimeout(function(){d.remove()},500)}b=$("#ProductAttributePanelIndexes").val();b=b==""?[]:b.split(",");c=$.inArray(c,b);c>=0&&b.splice(c,1);b=b.join(",");$("#ProductAttributePanelIndexes").val(b)};a.WriteIndexesCookie=function(b){$.cookie(this.IndexCookieKey,b)};a.GetIndexesCookie=function(){return parseInt($.cookie(this.IndexCookieKey))};
function InitShowOrHideAttributeGroupValueInput(b){var c=$("#"+("ProductAttributeGroupId_"+b)),d=$(c[0].options[c[0].selectedIndex]).attr("data");ShowOrHideAttributeGroupValueInput(b,d);c.bind("change",function(){var e=$(this.options[this.selectedIndex]).attr("data");ShowOrHideAttributeGroupValueInput(b,e)})}
function ShowOrHideAttributeGroupValueInput(b,c){var d="ProductAttribute"+c+"_"+b,e="ProductAttribute"+c+"Value_"+b,g="ProductAttributeTextValue_"+b;$("#ProductAttributePanel_"+b+" .input_div").each(function(){var f=$(this);if(f.attr("id")==d){f.show();g==e&&InitEditor(g)}else f.hide()})}function ClickAddProductAttributePanelBtn(b){b.AddProductAttributePanel();InitShowOrHideAttributeGroupValueInput(b.GetIndexesCookie())}
function DeleteProductAttribute(b,c,d){window.confirm("\u786e\u5b9a\u5220\u9664\u8be5\u4ea7\u54c1\u5c5e\u6027\u5417\uff1f")&&QueryAction(b,"ActionMessageBox","btnDeleteProductAttribute_"+d,function(){c.RemoveProductAttributePanel("ProductAttributePanel_"+d,d)});return false};
